### PR TITLE
System tray icons for system updates.

### PR DESCRIPTION
**Pull request by guoyunhe**
These icons can be used for plasma-pk-updates in system tray.

image

### CODE REVIEW

**Comment by DarkknightAK** [comment]
I'm not a big fan of the A cause what does the A mean update? aktualisieren? the sheeld is used cause this symbol was used in oxygen in windows, ... I'm not sure add a new symbol. not that easy to find a good symbol for update still the same problem than for install.

**Comment by guoyunhe** [comment]
Ubuntu update center is the design reference:
image

When there is only optional update (new features), it does not related to security, the shield.

And we also have system-software-update icon, which is a circle with up array. I can also make this style
image

**Comment by guoyunhe** [comment]
Changed to up arrow style. 


It follows the design of "system-software-update" icon, which is also used in plasma-pk-update.
image

**Comment by UriHerrera** [comment]
Add the icons to the dark theme too.

**Comment by guoyunhe** [comment]
Added.

**Comment by guoyunhe** [comment]
Can this pull-request be merged or it has any problems?

**Pull request merged**
