### PR TITLE
Add vcs icons

### PR DESCRIPTION
**Pull request by horosgrisa**
Add vcs icons for dolphin.
snapshot_wz5903

### CODE REVIEW

**Comment by DarkknightAK** [comment]
The red color isn't the red one from the breeze color table
https://github.com/NitruxSA/breeze-icon-theme/wiki/Icon-design-guidelines-in-Breeze#colors
can you push to kde:breeze-icons too?

**Comment by horosgrisa** [comment]
@DarkknightAK You can change color?

**Comment by horosgrisa** [comment]
@DarkknightAK And I can't push to kde:breeze-icons

**Comment by DarkknightAK** [comment]
I will push to kde:breeze-icons but please use the colors from the wiki

**Comment by horosgrisa** [comment]
@DarkknightAK See now

**Pull request merged**
