### PR TITLE
New icons for epiphany, gnome-tweak-tool and cheese

### PR DESCRIPTION
**Pull request by GabMus**
I added these three icons, epiphany is a webkit based browser for GNOME; gnome-tweak-tool is a customization tool for GNOME; cheese is a program to take photos with the webcam, again part of GNOME

Linked internet-web-browser.svg to web-browser for compatibility with epiphany
Added icon for gnome-tweak-tool
Added icon for cheese

### CODE REVIEW

**Comment by DarkknightAK** [comment]
Maybe you can work a little bit with the cheese app icons. there is to much information on the 48px icon. please remember that the 48px app icons were used also in the window decoration or the panel (default 22px in size)

**Comment by GabMus** [comment]
Thanks for the feedback, it's great to see an answer from you. I'll be working on it, sorry if it didn't meet your expectations, I'm not really a designer, it's more of a small hobby, but I'll try to do my best.

**Comment by DarkknightAK** [comment]
thank's for your contribution. most people do awesome work not in there job but in there spare time cause they love to do it.

**Comment by GabMus** [comment]
Made some small tweaks, tell me if you like it better

**Comment by DarkknightAK** [comment]
the smiley look a little scary maybe more funny and I'm not sure to add the "webcam" information cause cheese should work.

**Comment by GabMus** [comment]
Oh, well I think the smiley looks funny. I can tweak it, but being a little more specific could help :)
Also mind that I'm trying to mimic the original cheese icon, which looks like this
cheese

**Comment by DarkknightAK** [comment]
breeze also ship emoticons maybe you can use something from there. if you look at the app icons most of them don't fit that good the original icon. I only say please play a little bit AND test your icons in different size. you can also upload some examples and we can find the final icon.

**Comment by GabMus** [comment]
Ok, will probably do that in the next days. I have to admit that cheese is getting pretty difficult, in the meantime I tried to make another simple icon for another app, corebird, a twitter client. I'm pushing it in my fork, as a consequence it will end up in this pull request, so why not checking it out, too.

**Comment by DarkknightAK** [comment]
sure

**Pull request closed without merging**
