### PR TITLE
Create kube-mail.svg

### PR DESCRIPTION
**Pull request by AlessandroLongo**
kube-mail
Icon for Kube mail client

### CODE REVIEW

**Comment by DarkknightAK** [comment]
from my point of view it look unbalanced and to light also the K for Kube is not visible enough. maybe an additional color and the K more fancy.

**Comment by AlessandroLongo** [comment]
Better than nothing, if it respect Breeze guidelines please add it to the repo. If you want to improve it the SVG is there. And I'm here to discuss changes.

**Comment by DarkknightAK** [comment]
If you don't want to discuss move it to the kde breeze-icon repository by yourself. this is the working dictionary and here we discuss changes like dev's use reviewboard.

**Comment by AlessandroLongo** [comment]
I put it here to respect your workflow, if I made something wrong explain which is the correct way to contribute to Breeze.
I didn't say I don't want to discuss, I said please merge it and than start to discuss improvement. So the devs can have an icon for their project immediately.

**Comment by AlessandroLongo** [comment]
Is KDE repo for contributions only and the GitHub repo for discussions only?

**Comment by DarkknightAK** [comment]
the GitHub repo is for contributors and discussion and the kde repo is the official where the final work will be done. Here is something like playground.

If the dev's want to use this icon it is no problem cause they ship the application icon with there source code. our job is to have an consistent design for breeze.

**Comment by AlessandroLongo** [comment]
kube-mail-new
Better? When it's OK I will push it to master...

**Comment by DarkknightAK** [comment]
without the K yes but with the K it need something.

**Comment by AlessandroLongo** [comment]
kube-mail-new-2
Now?

**Comment by DarkknightAK** [comment]
thans for your kube app icon.

it was already merged and in in kde:breeze-icons too. 

keep up your great work

**Pull request closed without merging**
