### PR TITLE
Add Viber and Skype

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by UriHerrera** [comment]
Skype could use a gradient more akin to it's original and the gradient should begin and end at the same height of the icon so the colors are distributed evenly. The "S" shouldn't have transparency.

Viber should have _at least_ the background bubble speech.

**Comment by varlesh** [comment]
This style like?

**Comment by varlesh** [comment]
Viber?

**Comment by UriHerrera** [comment]
Good. Make the "S" white. Viber looks good.

**Pull request merged**
