### PR TITLE
Tool measure axes

### PR DESCRIPTION
**Pull request by tesfabpel**
Add axis "constraint" to 'tool-measure', representing the function to measure distances in a given axis.

### CODE REVIEW

**Comment by DarkknightAK** [comment]
hi tesfabpel,

I'm not sure this is a good idea cause you have a lot of information in this small icon.
1. the measure tool that say the user this is for measure something
2. the arrows for it's an line measure
3. the x, y, z it's for measure x, y, z

my question was:
1. where do you need this icon, for which application?
2. if you need x and y it would be better to have x = horizontal and y = vertical measure element
3. keep it simple

thanks that you support breeze-icons

**Comment by tesfabpel** [comment]
Hi,

I've designed these icons to represent measuring a dimension with a constraint to a given axis.
This may be useful in a CAD (2D and 3D) application.

Thanks :)

**Comment by DarkknightAK** [comment]
please add a screenshot from the application and maybe you can have a look in the libreoffice folder there I also have some axis icons.

**Comment by tesfabpel** [comment]
Hi,
In my opinion, the axis icons in the LibreOffice folder do not represent well the concept of getting a quote with a given axis constraint.

I found the cmd/lc_measureline.svg and cmd/sc_measureline.svg to represent better the concept (and they don't include a ruler which reduces the icon complexity). Maybe I could try adding the X, Y, and Z characters there...

I don't have any screenshot to show, because I'm just creating these icons to be used by anyone who is designing a CAD application with 3D capabilities.

Anyway, feel free to reject this pull request if there isn't a need for these icons... :)

**Comment by DarkknightAK** [comment]
Hi,

thanks for helping but it is not a good idea to add icons that wasn't used by anybody. It is way easier to add the right icon when you know what the icon was used. only freedesktop icons were added.

cu
Andreas

**Pull request closed without merging**
