### PR TITLE
Xterm icons

### PR DESCRIPTION
**Pull request by aldy-art**
Added Xterm icons.

xterm

### CODE REVIEW

**Comment by aldy-art** [comment]
This is the original icon. Both programs (UXTerm and XTerm) use the same icon.

xterm-icon

**Comment by aldy-art** [comment]
On the first icon I used lighter colors because the back color of xterm is white but maybe will be better to use the same colors of konsole. What do you think?

xterm-v2

**Comment by DarkknightAK** [comment]
you can use xterm in light and xterm-color in dark

**Comment by aldy-art** [comment]
Good idea.

**Pull request merged**
