### PR TITLE
Added icons for Kipi Plugins, Jdownloader and updated Synfig icon

### PR DESCRIPTION
**Pull request by aldy-art**
I did some icons for Digikam Kipi Plugins. You can compare the new ones on top with the originals on bottom. 

kipi-icons-comparison

And I updated the Synfig icon that I did last week and added an icon for Jdownloader. 
more-icons

### CODE REVIEW

**Comment by DarkknightAK** [comment]
thanks for starting with the kipi Plugins. I am not sure to add the digiKam icon in the kipi apps cause you can use them outside of digiKam and inside it is not seccessful. I Mike that the kipi plugins have the same brand but the icons should be easy recognition what's behind the app like the panorama icon. please update the kipi icons and extend to all plugins to have the same style.

thanks a lot keep up the great work

**Comment by aldy-art** [comment]
This is the second version. What do you think?

kipi-icons-comparison-v2

**Comment by DarkknightAK** [comment]
like the icon. I am not sure about the plugin symbol and the blue band maybe an kipi specific icon background shape. e.g. a lens or kamera shape.

**Comment by aldy-art** [comment]
Something like this?

kipi-icons-comparison-v3

**Comment by DarkknightAK** [comment]
awesome second row push it.

**Comment by aldy-art** [comment]
Done

**Comment by aldy-art** [comment]
What do you thing about using the icon "preferences-desktop-peripherals" for "input-tablet"? Because the KCM of the Wacom preferences and the notifications when you plug your tablet are still using the oxygen icon.

**Comment by DarkknightAK** [comment]
icons are in kde:breeze-icons too

**Pull request merged**
